name: Keep Replit Alive

on:
  schedule:
    # This cron job runs every 5 minutes.
    - cron: "*/5 * * * *"
  workflow_dispatch: # This allows manual triggering of the workflow if needed

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit
        run: |
          curl -fsS --retry 3 https://<your-replit-url>.repl.co
